# https://github.com/FduFinTech/LLaMA-Factory
CUDA_VISIBLE_DEVICES=0,1 python src/train_bash.py \
    --stage sft \
    --do_train \
    --model_name_or_path model_weight/Qwen-7B-Chat \
    --dataset llm_data_train \
    --template qwen \
    --finetuning_type lora \
    --lora_target c_attn \
    --output_dir path_to_sft_checkpoint \
    --overwrite_output_dir \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 2.0 \
    --plot_loss \
    --fp16
